---

- import_tasks: server.yml
  when: "ansible_distribution == 'Debian' and inventory_hostname == openvpn_server"
  tags:
    - openvpn

- import_tasks: client.yml
  when: "ansible_distribution == 'Debian' and inventory_hostname in openvpn_clients"
  tags:
    - openvpn
