---

- include: server.yml
  when: "ansible_distribution == 'Debian' and inventory_hostname == openvpn_server"
  tags:
    - openvpn

- include: client.yml
  when: "ansible_distribution == 'Debian' and inventory_hostname in openvpn_clients"
  tags:
    - openvpn
